### ISSUE TITLE
add logic for listing freelancers

### ISSUE THREAD

**Issue by daviidy** [daviidy/park-art#15]
@zamblebi please watch this video for more details <span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:28.025851938895418% 40.0117508813161%;background-size:5418.75% 5418.75%" data-codepoints="1f447-1f3fd"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:28.025851938895418% 40.0117508813161%;background-size:5418.75% 5418.75%" data-codepoints="1f447-1f3fd"></span></span><span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:28.025851938895418% 40.0117508813161%;background-size:5418.75% 5418.75%" data-codepoints="1f447-1f3fd"></span></span>

https://www.loom.com/share/f07a54f9653d42509d9c01175b0b9368

**Comment by eliphazbouye** [comment]
Logic for listing freelancer
Doing and pull request added on milestone-1 

Link to pull request
[https://github.com/daviidy/park-art/pull/26](url)

**Comment by eliphazbouye** [comment]
Small description on listing in coding ⏳

**Comment by daviidy** [comment]
What did you not understand?

**Comment by daviidy** [comment]
> Small description on listing in coding ⏳

What did you not understand?

**Comment by eliphazbouye** [comment]
Small text desciption fixed

Link to pull request : 
[https://github.com/daviidy/park-art/pull/29](url)

**Comment by eliphazbouye** [comment]
> What did you not understand?

???

**Comment by daviidy** [comment]
@zamblebi the freelancer avatar link is broken on the page 👇🏼👇🏼👇🏼

https://www.loom.com/share/ac2cb17586144b8bb4f42687c69e4ff0
