### ISSUE TITLE
showing user profile and edit user

### ISSUE THREAD

**Issue by daviidy** [daviidy/park-art#16]
- add logic for showing user profile (a client can see his profile on his dashboard
- add logic for editing user

**Comment by eliphazbouye** [comment]
- [ ]  add logic for showing user profile (a client can see his profile on his dashboard
- [ ] add logic for editing user


=== This is possible now I push it today . a client can see his dashboard and edit his profile

**Comment by daviidy** [comment]
Well, I don't see it yet. Did you add it to the view ?

**Comment by daviidy** [comment]
> - [ ]  add logic for showing user profile (a client can see his profile on his dashboard
> - [ ] add logic for editing user
> 
> 
> === This is possible now I push it today . a client can see his dashboard and edit his profile 

Well, I don't see it yet. Did you add it to the view ?

**Comment by eliphazbouye** [comment]
### Yes

**Comment by daviidy** [comment]
@zamblebi watch this video, please 👇🏼👇🏼👇🏼

https://www.loom.com/share/c17e62865b4b43f398a681132681646c
