### ISSUE TITLE
client avatar and typo

### ISSUE THREAD

**Issue by daviidy** [daviidy/park-art#18]
https://www.loom.com/share/9b40d245361448118ccdeb60eff4c568

**Comment by eliphazbouye** [comment]
Issue fixed

Link to pull request who solve this issue : 
[https://github.com/daviidy/park-art/pull/28](url)

**Comment by daviidy** [comment]
@zamblebi  changes requested:

- [ ] I cannot access the page for editing the client profile
- [ ] Therefore I cannot see my profile image or change it

**Comment by daviidy** [comment]
@zamblebi copy that 👇🏼👇🏼👇🏼
https://www.loom.com/share/d7f82987f2a844cd88858b649ffa8d33
