### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by soophoo** [daviidy/park-art#5]
For create new user
### **Warning 🚧 == 🚧**  
on database 'role' table add 2 new entry : 
id = 1 ; name = client
id = 2 ; name = freelancer
### **Warning 🚧 ==🚧**
with that you can register new user know

**Comment by eliphazbouye** [comment]
### **CRUD project information**

Link : for see projects add = /client/projects
Link for create new project = /client/projects/create
etc...
🚧 I wait more views for this crud 🚧

**Comment by daviidy** [comment]
> For create new user
> 
> ### **Warning == **
> on database 'role' table add 2 new entry :
> id = 1 ; name = client
> id = 2 ; name = freelancer
> 
> ### **Warning ==**
> with that you can register new user know

@zamblebi why did you use a role table ?

**Comment by aouman** [comment]
**Issue 🥇 ### Change design for projects list for user dashboard**

- Mise en place du nouveau designe de la liste des projets du client .

- Chemin : views/client/home.blade.php

### **issue 🥇 ### add page for showing a project**

- Mise en la place de la vue d'un projet.

- Chemin : views/client/project/show.blade.php

- J'ai mis le popup dans un include

- chemin popop : views/include/offert.blade.php

**Issue 🥇 ### add page for listing all the projects on the platforms**

- Mise en place de la page tous nos projets.

- Le chemin est views/projects/index.blade.php
